config/routes.rb
Rails.application.routes.draw do
  resources :reviews

  resources :pets

  resources :appointments, :only => [:create, :destroy]
  resources :poops
  
  post 'appointments/modal', to: 'appointments#modal'
  post 'appointments/send_text', to: 'appointments#send_text'
  post 'appointments/cancel', to: 'appointments#cancel'
  devise_for :users

  resources :users, :only => [:index, :show, :send_email] do
    resources :households
  end

  post 'users/send_email', to: 'users#send_email'

  root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :household, foreign_key: "owner_id", dependent: :destroy
  has_many :households, foreign_key: "walker_id"
  has_many :pets, through: :household
  has_many :appointments, foreign_key: "walker_id", dependent: :destroy
  has_many :reviews, foreign_key: "walker_id", dependent: :destroy
  has_many :reviews, foreign_key: "owner_id"

  validates_presence_of :name, :email

  mount_uploader :avatar, AvatarUploader

  validates_integrity_of  :avatar
  validates_processing_of :avatar

  def assign_household
    household = Household.find_by(email: self.email) 
    if household
      household.owner_name = self.name
      household.owner_id = self.id
      household.phone = self.phone
    else 
      household = Household.create(email: self.email, address: "Please update your profile with your current address.")
      household.owner_name = self.name
      household.owner_id = self.id
      household.phone = self.phone
      household.walker_id = 17
    end
    household.save
  end

  def all_pets
    self.households.collect { |house| house.pets }.flatten
  end

  def pet_owner_name
    User.find(@user.reviews.owner_id).name
  end

  def text_to_user(body, phone)
    @client = Twilio::REST::Client.new(ENV['TWILIO_SID'],ENV['TWILIO_AUTH_TOKEN'])
    @client.account.messages.create(
      :from => '+18037674105',
      :to => ENV['MY_PHONE'],
      :body => body
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show, :send_email]

  def send_email
    respond_to do |format|
      UserMailer.new_client_email(params).deliver
      format.html { redirect_to root_path, notice: 'Your email has been sent.'}
    end
  end
  
  def show
    if @user.admin == true
      @walkers = User.where(:walker => true)
      @owners = User.where(:walker => false)
      @households = Household.all
      @vets = Vet.all
      @pets = Pet.all
      render "admin.html.erb"
    elsif @user.walker == false
      if @user.household
        @appointments = @user.household.pets.collect { |pet| pet.appointments }.flatten.sort_by { |appt| appt.date }
      else
        @user.assign_household
        redirect_to current_user
      end
      @pet = Pet.new
      @walkers = User.where(walker: true)
      @review = Review.new
    else
      @pet = Pet.new
      @pets = @user.all_pets
      @appointments = @user.appointments.sort_by { |appt| appt.date }
      @appointment = Appointment.new
      @reviews = Review.where(:walker_id => params[:id])
    end
  end

  def index
    if signed_in?
      redirect_to current_user
    else
      @user = User.new
      @walkers = User.where(:walker => true).sample(3)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :phone, :walker, :avatar, :admin, :date, :walker_id, :owner_id, :text)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_clients.html.erb
<h2>Clients</h2>

<div class="panel-group" id="accordion">
  <% @user.households.each do |house| %>
    <div class="panel panel-default"> 
      <div class="panel-heading">
        <h5 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= house.id %>">
          <% if house.owner %>
            <h3><%= house.owner.name %></h3>
          <% else %>
            <h3><%= house.owner_name %></h3>
          <% end %>
          </a>
        </h5>
      </div>

      <div id="collapse<%= house.id %>" class="panel-collapse collapse">
        <div class="panel-body client">
          <h3><%= link_to house.address, user_household_path(@user.id, house) %>
          <small> | <%= link_to 'Edit Household Info', edit_user_household_path(@user.id, house) %> | <a id="pet-modal" data-target="#petModal" href="#" data-id="<%= house.id %>" data-value="<%= house.id %>">Add New Pet</a></h3> 
          <br>
          <div class="row">
            <% house.pets.each do |pet| %>
            <div class="col-sm-5 col-xs-12">
              <% if pet.avatar.url.present? %>
              <%= link_to image_tag(pet.avatar_url(:thumb)), pet_path(pet) %>
              <% else %>
              <%= link_to image_tag("thumb_dog_bounty.jpg"), pet_path(pet) %>
              <% end %>
              <br>
              <h4><%= link_to pet.name, pet_path(pet) %> | <small><%= link_to 'Edit Pet Info', edit_pet_path(pet) %></small></h4> 
              <br>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="modal fade" id="petModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Add a new pet</h4>
      </div>

      <div class="modal-body">
        <%= render 'pets/form' %>
      </div>

    </div>
  </div>
</div>

app/views/users/_owner.html.erb
<h2>Your Household</h2>
<p><small class="owner"><%= link_to 'Edit Household Info', edit_user_household_path(@user.household.walker_id, @user.household) %> | <a id="pet-modal" data-target="#petModal" href="#" data-id="<%= @user.household.id %>" data-value="<%= @user.household.id %>">Add New Pet</a></small></p>

<p><strong>Phone: </strong><%= @user.household.phone %></p>
<p><strong>Address:</strong> <%= @user.household.address %></p>

<p><strong>Pets:</strong></p>
<div class="row">
  <% @user.household.pets.each do |pet| %>
    <div class="col-sm-6 col-xs-12">
      <% if pet.avatar.url.present? %>
        <%= link_to image_tag(pet.avatar_url(:thumb)), pet_path(pet) %>
      <% else %>
        <%= link_to image_tag("thumb_dog_bounty.jpg"), pet_path(pet) %>
      <% end %>
      <p><%= link_to pet.name, pet_path(pet) %></p> 
      <p><small><%= link_to 'Edit Pet Info', edit_pet_path(pet) %></small></p>
      <br/>
    </div>
  <% end %>
</div>

<div class="modal fade" id="petModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Add a new pet</h4>
      </div>

      <div class="modal-body">
        <%= render 'pets/form' %>
      </div>

    </div>
  </div>
</div>

app/views/users/_reviews.html.erb
<% if @reviews %>
  <div class="row">
    <% @reviews.each do |review| %>
      <div class="col-xs-12">
        <div class="well well-sm">
          <h4><%= review.content %></h4>
          <h4><% review.rating.times do |star| %><span class="star">&#9733;</span><%end%> <small>out of 10</small></h4>
          <p>by <%= review.owner.name %></p>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="well"> No reviews yet! </div>
  <br />
<% end %>

app/views/users/admin.html.erb
<h1>Admin Page</h1>

<div class="row">
  <div class="col-xs-12">
    <div class="well">
      <h2>Walkers</h2>
      <div class="table-responsive">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
          <tr>
        </thead>
        <tbody>
          <% @walkers.each do |walker| %>
            <tr>
              <td><div class="photo-sm"><%= image_tag walker.avatar_url(:thumb)%></div></td>
              <td><%= link_to walker.name, walker %></td>
              <td><%= walker.email %></td>
              <td><%= walker.phone %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  </div>

  <div class="col-xs-12">
    <div class="well">
      <h2>Owners</h2>
      <div class="table-responsive">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Address</th>
          <tr>
        </thead>
        <tbody>
          <% @owners.each do |owner| %>
            <tr>
              <td><div class="photo-sm"><%= image_tag owner.avatar_url(:thumb)%></div></td>
              <td><%= link_to owner.name, owner %></td>
              <td><%= owner.email %></td>
              <td><%= owner.phone %> <%= owner.household.phone if owner.household %></td>
              <td><%= owner.household.address if owner.household %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
  </div>

  <div class="col-xs-12">
    <div class="well">
      <h2>Pets</h2>
      <div class="table-responsive">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Species</th>
            <th>Size</th>
            <th>Age</th>
            <th>Vet</th>
            <th></th>
            <th></th>
          <tr>
        </thead>
        <tbody>
          <% @pets.each do |pet| %>
            <tr>
              <td><div class="photo-sm"><%= image_tag pet.avatar_url(:thumb)%></div></td>
              <td><%= link_to pet.name, pet %></td>
              <td><%= pet.species %></td>
              <td><%= pet.size %> </td>
              <td><%= pet.age %> </td>
              <td><%= pet.vet.name if pet.vet %> </td>
              <td class="text-center"><%= link_to 'Edit', edit_pet_path(pet) %></td>
              <td class="text-center"><%= link_to 'Remove', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  </div>

  <div class="col-xs-12">
    <div class="well">
      <h2>Vets</h2>
      <div class="table-responsive">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Address</th>
          <tr>
        </thead>
        <tbody>
          <% @vets.each do |vet| %>
            <tr>
              <td><%= vet.name %></td>
              <td><%= vet.phone %></td>
              <td><%= vet.address %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</div>


<script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script>
  $(function() {
    $( "#accordion" ).accordion();
  });
</script>

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <p id="notice"><%= notice %></p>
    
    <div class="jumbotron">
      <h1>Dog walker?<span class="subheader1"> Cat sitter? </span><span class="subheader2">Armadillo wrangler?</span></h1>
      <h4>
        <%= link_to "Sign up", new_registration_path(@user), type: "button", class: "btn-lg btn-primary" %> <span class="spaced">or</span> <%= link_to "Check Out the Demo", new_user_session_path, type: "button", class: "btn-lg btn-primary" %>
      </h4>
    </div>
  </div> 

  <div class="col-md-10 col-xs-12"> 
    <h1 class="home-header" style="margin-bottom: -5px;">Need help with your pet?</h1>
    <h3>Check out our amazing pet sitters!</h3>
  </div>
</div>

<div class="row contact-walker">
  <% @walkers.each do |walker| %>
    <div class="col-md-4">
      <div class="well walkers">
        <div class="row">
          <div class="col-md-4">
            <p><div class="photo-sm"><%= image_tag walker.avatar_url.to_s %></div></p>
            <h3><%= link_to walker.name, walker %></h3>
            <br>
            <button class="btn btn-primary" id="email-modal-button" data-target="#myModal" id="walker" data-id="<%= walker.id %>">Send email</button>
          </div>

          <div class="col-md-7 col-md-offset-1">
            <h4>Reviews</h4>
            <ul>
              <% Review.where(:walker_id => walker.id).each do |review| %>
                <li><%= review.content %> <p><% review.rating.times do |star| %><span class="star">&#9733;</span><%end%></p></li>
              <% end %>
            </ul> 
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Get in touch!</h4>
      </div>

      <div class="modal-body">
                
        <%= form_tag("/users/send_email", method: "post") do %>
          <div class="field">
            <p>Please fill out the form below.</p>
          </div>

          <input type="hidden" name="walker_id" id="walker" value=""/>

          <div class="field">
            <%= label_tag :name %><br>
            <%= text_field_tag :name, "Joe Owner" %>
          </div>

          <div class="field">
            <%= label_tag :phone %><br>
            <%= text_field_tag :phone, "555-555-5555" %>
          </div>

          <div class="field">
            <%= label_tag :email %><br>
            <%= text_field_tag :email, "joe@joe.com" %>
          </div>

          <div class="field">
            My pet is a: 
            <select>
              <option value="cat">cat</option>
              <option value="dog">dog</option>
              <option value="other">other</option>
            </select>
          </div>

          <div class="field">
            </strong>Message (optional)</strong><br/>
            <textarea rows="2" cols="50" type="text" name="text" id="text" placeholder="I want to hire you!"></textarea>
          </div>

          <div class="actions" id="send-email">
            <%= submit_tag("Send Email") %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-8 col-xs-12">
    <% if current_user %>
      <% if @user.walker == true %>
        <%= render "appointments/appointments" %>
      <% else %>
        <%= render "appointments/schedule" %>
      <% end %>
    <% end %>

    <% if current_user && @user.walker == true %>
      <div class="well">
        <%= render "clients" %>
      </div>
    <% elsif current_user && @user.walker == false %>
      <div class="well">
        <div class="row">
          <div class="col-md-6 col-xs-12">
            <h2>Your Walker</h2>
            <p><%= image_tag @user.household.walker.avatar_url(:thumb) %></p>
            <% if @user.household.walker.id == 17 %>
              Please chose a walker below.
            <% else %>
              <h3><%= @user.household.walker.name %></h3>
              <h5><%= @user.household.walker.email %></h5>
              <h5><%= @user.household.walker.phone %></h5>
            <% end %>
            <br>
            <%= form_tag(user_household_path(@user.household.walker_id, @user.household), :method => :put) do %>
              <div class="field">
                <p><%= label_tag "Choose a new walker:" %><br>
                <%= collection_select :household, :walker_id, @walkers, :id, :name, prompt: "Select Walker" %></p>
              </div>

              <div class="actions">
                <%= submit_tag "Choose Walker", class:"btn btn-primary" %>
              </div>
            <% end %>
          </div>

          <div class="col-md-6 col-xs-12">
            <%= render "reviews/form" %>
          </div>
        </div>
      </div>
    <% end %>

    <% unless @user.walker == false %>
      <div class="well well-lg">
        <h2>Reviews
          <button type="button" class="btn btn-primary pull-right" aria-expanded="false" data-toggle="collapse" data-target="#reviews">Hide</button>
        </h2>
          <div id="reviews" class="collapse in">
            <%= render "reviews" %>
          </div>
      </div>
    <% end %>
  </div>

  <div class="col-sm-4 col-xs-12">
    <% if @user.walker == true || current_user %>
      <div class="well">
        <div class="photo-lg">
        <%= image_tag @user.avatar_url.to_s %>
        </div>
        <h1><%= @user.name %></h1>
        <h4><%= @user.email %></h4>
        <h4><%= @user.phone %></h4>
      <% if @user.walker == false %>
        <h4><%= @user.household.address %></h4>
      <% end %>

      <% if current_user == @user %>
        <div class="links">
          <br>
          <p><%= link_to 'Edit Profile', edit_user_registration_path %> 
          <% if @user.walker == true %>
            | <%= link_to 'Add a New Client', new_user_household_path(@user) %>
          <% end %></p>
        </div>
      <% end %>
      </div>
    <% end %>

    <% if current_user && @user.walker == false %>
      <div class="well">
        <%= render "owner" %>
      </div>
    <% end %>

  </div>
</div>