config/routes.rb
Rails.application.routes.draw do
  resources :reviews

  resources :pets

  resources :appointments, :only => [:create, :destroy]
  resources :poops
  
  post 'appointments/modal', to: 'appointments#modal'
  post 'appointments/send_text', to: 'appointments#send_text'
  post 'appointments/cancel', to: 'appointments#cancel'
  devise_for :users

  resources :users, :only => [:index, :show, :send_email] do
    resources :households
  end

  post 'users/send_email', to: 'users#send_email'

  root 'users#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
    @users = User.where(walker: true)
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    respond_to do |format|
      if @review.save
        format.html { redirect_to current_user, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:content, :rating, :walker_id, :owner_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
  <h2>Write a Review</h2>
  <%= form_for(@review) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <p><%= f.label :walker_id %><br>
      <%= f.collection_select :walker_id, @walkers, :id, :name, prompt: "Select Walker" %></p>
    </div>
    <div class="field">
      <p><%= f.label :content %><br>
      <%= f.text_area :content %></p>
    </div>
    <div class="field">
      <p><%= f.label :rating %> (0-10 scale)<br>
      <%= f.number_field :rating, in: 0..10 %></p>
    </div>
    <div class="field">
      <%= f.hidden_field :owner_id, value: @user.id %>
    </div>
    <div class="actions">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.content %></td>
        <td><%= review.rating %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>